server:
  port: ${SERVER_PORT:8086}

elasticsearch:
  host: localhost
  port: 9201
  scheme: http
  index: businesses

spring:
  application:
    name: elastic-search-demo

  datasource:
    url: jdbc:postgresql://localhost:5434/esdemo
    driver-class-name: org.postgresql.Driver
    username: esdemo
    password: esdemo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  datasource.hikari:
    maximum-pool-size: 10
    connection-timeout: 30000

logging:
  level:
    com.example.esdemo: INFO
    org.hibernate.SQL: WARN
