services:
  gopuff-db:
    image: postgres:16-alpine
    container_name: gopuff-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: gopuff
      POSTGRES_USER: gopuff
      POSTGRES_PASSWORD: gopuff123
    volumes:
      - gopuff-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gopuff -d gopuff"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  gopuff-redis:
    image: redis:7-alpine
    container_name: gopuff-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  gopuff-pgdata:
